// data.jsx — content for the DCT Abu Dhabi frontline app prototype

const PERSONAS = {
  concierge: {
    id: 'concierge',
    name: 'Leila Haddad',
    role: 'Concierge',
    venue: 'Emirates Palace',
    avatar: 'LH',
    tier: 'Gold Host',
    points: 4820,
    xp: 1240,
    xpNext: 1500,
    rank: 12,
    badges: 7,
  },
  taxi: {
    id: 'taxi',
    name: 'Rajesh Kumar',
    role: 'Taxi Driver',
    venue: 'TransAD · Fleet 204',
    avatar: 'RK',
    tier: 'Silver Host',
    points: 2140,
    xp: 680,
    xpNext: 1000,
    rank: 48,
    badges: 4,
  },
  info: {
    id: 'info',
    name: 'Maria Santos',
    role: 'Info Desk Agent',
    venue: 'Zayed Intl. Airport',
    avatar: 'MS',
    tier: 'Gold Host',
    points: 3960,
    xp: 1020,
    xpNext: 1500,
    rank: 18,
    badges: 6,
  },
};

// Real Abu Dhabi imagery (Unsplash — license-free)
const IMG = {
  foodFestival: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
  louvre:       'https://images.unsplash.com/photo-1570129476814-ecc14d33d2f8?w=800&q=80',
  ramadan:      'https://images.unsplash.com/photo-1591456983933-0b18c9954a17?w=800&q=80',
  corniche:     'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800&q=80',
  yasMarina:    'https://images.unsplash.com/photo-1551292831-023188e78222?w=800&q=80',
  mosque:       'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80',
  desert:       'https://images.unsplash.com/photo-1547721064-da6cfb341d50?w=800&q=80',
  skyline:      'https://images.unsplash.com/photo-1548192746-dd526f154ed9?w=800&q=80',
};

// Feed item types: announcement | lesson | shoutout | alert | course | badge
const FEED = [
  {
    id: 'f1',
    type: 'alert',
    pillar: 'comms',
    priority: true,
    author: 'DCT Command',
    authorBadge: 'OFFICIAL',
    time: '2m',
    title: 'Service diversions around Corniche — F1 setup begins tonight',
    body: 'Lanes 2–4 closed 22:00–05:00 through Friday. Use the inland service road. Guests asking for airport pickup: add 15 min.',
    tag: 'Priority alert',
    scene: 'corniche',
  },
  {
    id: 'f2',
    type: 'announcement',
    pillar: 'comms',
    author: "What's On, Abu Dhabi",
    time: '1h',
    title: 'Abu Dhabi Food Festival opens Thursday at Umm Al Emarat Park',
    body: '80+ stalls, nightly performances, free entry with Emirates ID. Running through Dec 1.',
    image: 'food-festival',
    scene: 'foodFestival',
    saved: false,
    tag: 'What\'s on',
  },
  {
    id: 'f3',
    type: 'lesson',
    pillar: 'learning',
    author: 'VX Academy',
    time: '3h',
    title: 'VX Destination Challenge — can you guess which Abu Dhabi icon I am?',
    body: 'Known for art, culture, and iconic architecture. Located on Saadiyat Island. Tap the answer — instant feedback.',
    reward: { points: 25, xp: 10 },
    duration: '30 sec',
    tag: 'Destination Challenge',
  },
  {
    id: 'f4',
    type: 'shoutout',
    pillar: 'recognition',
    author: 'Peer shout-out',
    time: '5h',
    title: 'Hamad nominated you for "Above & Beyond"',
    body: '"Leila walked our guests all the way to Louvre AD when their driver no-showed. Pure class." — 23 others cheered.',
    tag: 'Recognition',
  },
  {
    id: 'f5',
    type: 'course',
    pillar: 'learning',
    author: 'DCT Academy',
    time: '1d',
    title: 'New course: Cultural Etiquette for Ramadan Season',
    body: '6 modules · earn the Ramadan Ready badge and 150 points on completion.',
    image: 'course-ramadan',
    scene: 'ramadan',
    cta: 'Start course',
    tag: 'LMS · New',
  },
  {
    id: 'f6',
    type: 'announcement',
    pillar: 'comms',
    author: 'Abu Dhabi Calendar',
    time: '1d',
    title: 'Louvre Abu Dhabi late nights every Thursday',
    body: 'Open till 22:00 with live oud performances in the dome. Complimentary entry for frontline pass holders.',
    image: 'louvre',
    scene: 'louvre',
    tag: 'What\'s on',
  },
  {
    id: 'f7',
    type: 'badge',
    pillar: 'recognition',
    author: 'Recognition',
    time: '2d',
    title: 'You earned the "First Responder" badge',
    body: 'For completing 5 guest-assistance reports in one week. +200 points.',
    tag: 'Badge unlocked',
  },
];

const BADGES = [
  { id: 'b1', name: 'First Responder', earned: true, icon: '\u25C6', desc: '5 guest assists in a week' },
  { id: 'b2', name: 'City Whisperer', earned: true, icon: '\u25C9', desc: '10 "what\'s on" questions answered' },
  { id: 'b3', name: 'Lesson Streak 7', earned: true, icon: '\u25C8', desc: '7 days of micro-lessons' },
  { id: 'b4', name: 'Ramadan Ready', earned: false, icon: '\u25C7', desc: 'Complete the Ramadan course' },
  { id: 'b5', name: 'Polyglot', earned: true, icon: '\u25CA', desc: 'Passed 3 language refreshers' },
  { id: 'b6', name: 'Night Owl', earned: false, icon: '\u25CB', desc: '20 shifts after 22:00' },
  { id: 'b7', name: 'Five-Star', earned: true, icon: '\u2605', desc: 'Rated 5\u2605 by 25 guests' },
  { id: 'b8', name: 'Above & Beyond', earned: true, icon: '\u2756', desc: '3 peer nominations' },
];

const LEADERBOARD = [
  { rank: 1, name: 'Fatima Al Mansoori', venue: 'Yas Marina', points: 8920, delta: '+340', avatar: 'FA' },
  { rank: 2, name: 'Daniel Okafor', venue: 'Louvre Abu Dhabi', points: 7640, delta: '+210', avatar: 'DO' },
  { rank: 3, name: 'Priya Sharma', venue: 'Zayed Airport', points: 7120, delta: '+180', avatar: 'PS' },
  { rank: 4, name: 'Ahmed Saleh', venue: 'Qasr Al Watan', points: 6480, delta: '+95', avatar: 'AS' },
  { rank: 5, name: 'Grace Mensah', venue: 'Emirates Palace', points: 5910, delta: '+120', avatar: 'GM' },
];

// ─── Learning modules & units ─────────────────────────────────
const LEARNING_MODULES = [
  {
    id: 'soft',
    name: 'Guest Experience Essentials',
    desc: 'Communication, empathy, de-escalation',
    totalUnits: 36,
    completedUnits: 12,
    icon: '🎯',
    color: '#F15A3A',
    units: [
      { id: 's1', name: 'Active listening fundamentals', duration: '2:30', points: 15, completed: true },
      { id: 's2', name: 'Reading body language', duration: '2:45', points: 20, completed: true },
      { id: 's3', name: 'Empathy in high-stress moments', duration: '3:00', points: 20, completed: true },
      { id: 's4', name: 'Greeting guests warmly', duration: '2:15', points: 15, completed: true },
      { id: 's5', name: 'De-escalation techniques', duration: '2:50', points: 25, completed: true },
      { id: 's6', name: 'Handling complaints gracefully', duration: '3:10', points: 25, completed: true },
      { id: 's7', name: 'Cross-cultural sensitivity', duration: '2:40', points: 20, completed: true },
      { id: 's8', name: 'Tone & word choice', duration: '2:20', points: 15, completed: true },
      { id: 's9', name: 'Building rapport quickly', duration: '2:35', points: 20, completed: true },
      { id: 's10', name: 'Apologizing with sincerity', duration: '2:25', points: 15, completed: true },
      { id: 's11', name: 'Managing expectations', duration: '2:55', points: 20, completed: true },
      { id: 's12', name: 'Non-verbal communication', duration: '2:30', points: 15, completed: true },
      { id: 's13', name: 'Phone etiquette essentials', duration: '2:40', points: 20, completed: false },
      { id: 's14', name: 'Upselling without pressure', duration: '3:00', points: 25, completed: false },
      { id: 's15', name: 'Delivering bad news', duration: '2:50', points: 20, completed: false },
      { id: 's16', name: 'Conflict mediation basics', duration: '3:05', points: 25, completed: false },
      { id: 's17', name: 'Teamwork & collaboration', duration: '2:30', points: 15, completed: false },
      { id: 's18', name: 'Time management under pressure', duration: '2:45', points: 20, completed: false },
      { id: 's19', name: 'Maintaining composure', duration: '2:20', points: 15, completed: false },
      { id: 's20', name: 'Asking clarifying questions', duration: '2:35', points: 15, completed: false },
      { id: 's21', name: 'Positive reinforcement', duration: '2:25', points: 15, completed: false },
      { id: 's22', name: 'Feedback: giving & receiving', duration: '2:55', points: 20, completed: false },
      { id: 's23', name: 'Patience in repetitive tasks', duration: '2:40', points: 15, completed: false },
      { id: 's24', name: 'Building trust', duration: '2:50', points: 20, completed: false },
      { id: 's25', name: 'Adaptability & flexibility', duration: '2:30', points: 15, completed: false },
      { id: 's26', name: 'Professionalism in dress & demeanor', duration: '2:15', points: 15, completed: false },
      { id: 's27', name: 'Respecting boundaries', duration: '2:40', points: 20, completed: false },
      { id: 's28', name: 'Multitasking strategies', duration: '2:50', points: 20, completed: false },
      { id: 's29', name: 'Storytelling for engagement', duration: '3:00', points: 25, completed: false },
      { id: 's30', name: 'Handling language barriers', duration: '2:45', points: 20, completed: false },
      { id: 's31', name: 'Expressing gratitude', duration: '2:20', points: 15, completed: false },
      { id: 's32', name: 'Staying motivated', duration: '2:30', points: 15, completed: false },
      { id: 's33', name: 'Emotional intelligence', duration: '3:10', points: 25, completed: false },
      { id: 's34', name: 'Personal accountability', duration: '2:35', points: 15, completed: false },
      { id: 's35', name: 'Dealing with fatigue', duration: '2:25', points: 15, completed: false },
      { id: 's36', name: 'Celebrating small wins', duration: '2:15', points: 15, completed: false },
    ],
  },
  {
    id: 'destination',
    name: 'Destination Knowledge',
    desc: 'Landmarks, culture, attractions, events',
    totalUnits: 28,
    completedUnits: 5,
    icon: '🗺️',
    color: '#3B2B6B',
    units: [],
  },
  {
    id: 'cultural',
    name: 'Cultural Awareness',
    desc: 'Traditions, etiquette, guest sensitivity',
    totalUnits: 18,
    completedUnits: 3,
    icon: '🌍',
    color: '#1F7A4C',
    units: [],
  },
  {
    id: 'service',
    name: 'Service Excellence',
    desc: 'Hospitality standards, recovery, VIP handling',
    totalUnits: 22,
    completedUnits: 6,
    icon: '⭐',
    color: '#C8253A',
    units: [],
  },
];

const COURSES = [
  { id: 'c1', name: 'Guest Experience Essentials', mods: 6, progress: 0.75, reward: '50 pts', status: 'in-progress', duration: '28 min' },
  { id: 'c2', name: 'Destination Knowledge — Abu Dhabi', mods: 5, progress: 0.4, reward: '100 pts + Badge', status: 'in-progress', duration: '22 min' },
  { id: 'c3', name: 'Cultural Awareness for Ramadan', mods: 4, progress: 0, reward: '150 pts + Badge', status: 'new', duration: '18 min' },
  { id: 'c4', name: 'Service Excellence Standards', mods: 3, progress: 1, reward: '120 pts + Badge', status: 'complete', duration: '12 min' },
  { id: 'c5', name: 'Arabic phrases for frontline hosts', mods: 8, progress: 0, reward: '200 pts + Badge', status: 'new', duration: '40 min' },
];

// ─── Rewards catalog ──────────────────────────────────────────
// `kind: 'dct'`   → DCT-licensed venues (hotels, museums, attractions) — DCT's own leverage
// `kind: 'partner'` → everyday brands (groceries, telecom, fuel, ride)
// `audience: [...]` → personas this resonates with most (for "For you" surfacing)
// Personas: 'concierge' | 'taxi' | 'info'
const COUPONS = [
  // ── DCT ECOSYSTEM — "Experience Abu Dhabi" ──
  { id: 'dct1', kind: 'dct', category: 'Hotel',       brand: 'Emirates Palace Mandarin Oriental', title: 'Dinner for two at Hakkasan',         cost: 1800, expires: 'Feb 28', color: '#8a6d3b', audience: ['concierge','info'], scene: 'corniche' },
  { id: 'dct2', kind: 'dct', category: 'Hotel',       brand: 'Saadiyat Rotana Resort',  title: 'One-night stay \u00B7 weekday',          cost: 3200, expires: 'Mar 31', color: '#3B2B6B', audience: ['concierge','info'], scene: 'corniche' },
  { id: 'dct3', kind: 'dct', category: 'Attraction',  brand: 'Louvre Abu Dhabi',        title: 'Complimentary entry for two',       cost: 450,  expires: 'Jan 31', color: '#2a4d6e', audience: ['concierge','info','taxi'], scene: 'louvre' },
  { id: 'dct4', kind: 'dct', category: 'Attraction',  brand: 'Natural History Museum AD', title: 'One-day entry pass',              cost: 380,  expires: 'Feb 15', color: '#1F7A4C', audience: ['concierge','info','taxi'], scene: 'corniche' },
  { id: 'dct5', kind: 'dct', category: 'Leisure',     brand: 'Saadiyat Beach Club',     title: 'Pool day pass \u00B7 weekdays',          cost: 600,  expires: 'Feb 28', color: '#1c6b8c', audience: ['concierge','taxi','info'], scene: 'corniche' },
  { id: 'dct6', kind: 'dct', category: 'Attraction',  brand: 'Qasr Al Watan',           title: 'Free guided palace tour',           cost: 350,  expires: 'Jan 15', color: '#6b4a2a', audience: ['concierge','info','taxi'], scene: 'louvre' },
  { id: 'dct7', kind: 'dct', category: 'Hotel',       brand: 'Rixos Marina \u00B7 Yas Island', title: 'Family Sunday brunch for 4',      cost: 2400, expires: 'Feb 28', color: '#C8253A', audience: ['concierge','info'], scene: 'foodFestival' },
  { id: 'dct8', kind: 'dct', category: 'Leisure',     brand: 'Yas Waterworld',          title: '30% off weekday pass',              cost: 500,  expires: 'Feb 28', color: '#1c6b8c', audience: ['taxi','info','concierge'], scene: 'corniche' },

  // ── EVERYDAY PARTNERS ──
  { id: 'pt1', kind: 'partner', category: 'Groceries', brand: 'Carrefour',         title: 'AED 50 off groceries over 200', cost: 180, expires: 'Dec 31', color: '#0057a6', audience: ['taxi','info','concierge'] },
  { id: 'pt2', kind: 'partner', category: 'Telecom',   brand: 'Etisalat by e&',    title: 'AED 40 mobile recharge',        cost: 160, expires: 'Jan 20', color: '#C8253A', audience: ['taxi','info'] },
  { id: 'pt3', kind: 'partner', category: 'Telecom',   brand: 'du',                title: 'AED 30 data add-on',            cost: 130, expires: 'Jan 31', color: '#141414', audience: ['taxi','info'] },
  { id: 'pt4', kind: 'partner', category: 'Fuel',      brand: 'ADNOC',             title: 'AED 30 fuel credit',            cost: 150, expires: 'Jan 20', color: '#1a6b3e', audience: ['taxi'] },
  { id: 'pt5', kind: 'partner', category: 'Groceries', brand: 'LuLu Express',      title: '15% off fresh produce',         cost: 120, expires: 'Dec 28', color: '#b8312a', audience: ['taxi','info','concierge'] },
  { id: 'pt6', kind: 'partner', category: 'Groceries', brand: 'Al Maya Supermarket', title: 'AED 25 off essentials',       cost: 90,  expires: 'Jan 10', color: '#F15A3A', audience: ['taxi','info'] },
  { id: 'pt7', kind: 'partner', category: 'Ride',      brand: 'Careem',            title: 'AED 25 ride credit',            cost: 130, expires: 'Dec 25', color: '#0e7a4b', audience: ['info','concierge'] },
  { id: 'pt8', kind: 'partner', category: 'F&B',       brand: 'Noon Food',         title: 'AED 40 off your next order',    cost: 160, expires: 'Jan 15', color: '#feee00', textDark: true, audience: ['taxi','info','concierge'] },

  // ── EXCLUSIVE FRONTLINER OFFERS (free, no points needed) ──
  { id: 'ex1', kind: 'exclusive', category: 'Coffee',   brand: '%Arabica',          title: 'Free coffee every Friday',      cost: 0, expires: 'Ongoing', color: '#2c2c2c', audience: ['concierge','info','taxi'] },
  { id: 'ex2', kind: 'exclusive', category: 'Meals',    brand: 'Jones the Grocer',  title: 'Meal deal — AED 29 lunch set',  cost: 0, expires: 'Ongoing', color: '#4a7a3a', audience: ['concierge','info','taxi'] },
  { id: 'ex3', kind: 'exclusive', category: 'Retail',   brand: 'Sharaf DG',         title: '15% off electronics',           cost: 0, expires: 'Mar 31',  color: '#0057a6', audience: ['taxi','info','concierge'] },
  { id: 'ex4', kind: 'exclusive', category: 'Wellness', brand: 'Fit Republic',      title: 'Free trial week membership',    cost: 0, expires: 'Feb 28',  color: '#E08264', audience: ['concierge','info','taxi'] },
  { id: 'ex5', kind: 'exclusive', category: 'Family',   brand: 'Yas Theme Parks',   title: 'Kids go free on weekdays',      cost: 0, expires: 'Mar 31',  color: '#1c6b8c', audience: ['concierge','info','taxi'], scene: 'corniche' },
  { id: 'ex6', kind: 'exclusive', category: 'Attractions', brand: 'Qasr Al Hosn',   title: 'Complimentary entry for frontliners', cost: 0, expires: 'Ongoing', color: '#6b4a2a', audience: ['concierge','info','taxi'], scene: 'louvre' },
];

Object.assign(window, { PERSONAS, FEED, BADGES, LEADERBOARD, COURSES, LEARNING_MODULES, COUPONS });
